remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "/"
footer_text: "Thanks to Ankit Sultana for the base layout :)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Fun"
   link: "https://www.youtube.com/watch?v=ZABuNa65Rik"
